export const data = [
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
]
