import Grid from "@material-ui/core/Grid"
import { withInfo } from "@storybook/addon-info"
import { storiesOf } from "@storybook/react"
import * as React from "react"
import SimpleTable from "."
;(storiesOf("Table", module) as any)
  .addDecorator(withInfo({ text: `Description!`, inline: true }))
  .add("Simple Table", () => (
    <Grid container={true} justify="center" style={{ padding: 50 }}>
      <Grid item={true} xs={10} style={{ padding: 20 }}>
        <SimpleTable data={data} />
      </Grid>
    </Grid>
  ))
// .addWithJSX("Error", () => <Button error>1234567</Button>)

export const data = [
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
]
